name: Multi-Platform SpringBoot Native Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [windows-latest]
    steps:
      # 1. 检出代码
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. 安装 GraalVM
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'          # GraalVM JDK 版本
          distribution: 'graalvm'
          components: 'native-image'  # 安装 native-image 工具
          cache: maven                # 启用 Maven 缓存
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      # 3. 先安装父模块和公共模块到本地仓库
      - name: Install parent and shared modules
        run: mvn clean install -DskipTests -B

      # 4. 构建 Native 镜像
      - name: Build native image
        run: mvn -Pnative native:compile -DskipTests -B

      # 5. 上传构建产物（可选）
      - name: Upload native binary
        uses: actions/upload-artifact@v4
        with:
          name: springboot-native-${{ matrix.os }}
          path: |
            **/target/*.exe
            **/target/*-runner
