name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: GraalVM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # 操作系统
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run 
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: using Maven plugin
        run: |
         # cd ./bingo-app
         # mvn clean native:compile -Pnative
         mvn -B native:compile --file bingo/pom.xml -Pnative
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: GraalVM-${{ matrix.os }}
          path: path/to/artifact
